### ISSUE TITLE
Document maven_install.json format

### ISSUE THREAD

**Issue by gonzojive** [bazel-contrib/rules_jvm_external#1259]
I'm working on a gazelle plugin for kotlin that uses maven_install.json files to help compute a (java package <-> bazel target) mapping.

I haven't found documentation for maven_install.json. It seems there are two versions of this file (v1 and v2 is what they are called in the java/gazelle/private/maven Go code in rules_jvm.

Here's the code that writes the lockfile in this repo:

https://github.com/bazel-contrib/rules_jvm_external/blob/d45e59ee582c2999dabbccab43320ce92d5bb0ee/private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/cmd/Main.java#L258-L309

I think the format should be documented, at least in internal comments.

**Comment by shs96c** [comment]
The format isn't documented as it might change. However, the mapping of java package to bazel target is already managed in the java gazelle plugin, and you can get access to for a gazelle plugin by importing https://github.com/bazel-contrib/rules_jvm/blob/43d61cb52dc0752a9834b212cd2d5d69dec3d4cf/java/gazelle/private/maven/resolver.go#L44

**Comment by gonzojive** [comment]
That code is lacking in godoc. I meant for the issue to track adding
comments to that code or putting a description in some internal document.
